  name: Flask App CI/CD Pipeline
  on:
    push:
      branches: ["staging"]

  jobs:
    python_setup:
      runs-on: ubuntu-latest
      env:
        MONGO_URI: ${{ vars.MONGO_URI }}
        SECRET_KEY: ${{ vars.SECRET_KEY }}
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4
        - name: Python Setup
          uses: actions/setup-python@v4
        - name: Install Dependencies
          run: |
            pip install -r requirements.txt
        - name: Test Before Deployment
          run: |
            pytest

    # test:
    #   runs-on: ubuntu-latest
    #   needs: python_setup
    #   steps:
    #     - name: Test Before Deployment
    #       run: |
    #         pytest
        # - name: build docker image
        #   run: |
        #     docker build -t test:01 ./backend
        # - name: Test the image
        #   run: |
        #     docker run -itd test:01 bash
        

