  name: Flask App CI/CD Pipeline
  on:
    push:
      branches: ["staging"]

  jobs:
    python_setup:
      runs-on: ubuntu-latest
      services:
        mongo:
          image: mongo:6
          ports:
            - 27017:27017
      env:
        MONGO_URI: mongodb://localhost:27017/test_student_db
        SECRET_KEY: test-secret-key
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4
        - name: Python Setup
          uses: actions/setup-python@v4
        - name: Install Dependencies
          run: |
            pip install -r requirements.txt
        - name: Test Before Deployment
          run: |
            pytest
        - name: Build the Image
          run: |
            docker build -t test:01 .
        - name: Deploy to Staging Branch
          run: |
            docker run -itd -p 5000:5000 test:01
        - name: Wait for Flask
          run: |
            sleep 5
        - name: Check health
         run: |
           curl http://localhost:5000/health

    # test:
    #   runs-on: ubuntu-latest
    #   needs: python_setup
    #   steps:
    #     - name: Test Before Deployment
    #       run: |
    #         pytest
        # - name: build docker image
        #   run: |
        #     docker build -t test:01 ./backend
        # - name: Test the image
        #   run: |
        #     docker run -itd test:01 bash
        

